import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const sourceDirectory = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(sourceDirectory, '../..');
const outputPath = resolve(packageRoot, 'lib/index.js');

const result = await build({
  entryPoints: [resolve(sourceDirectory, 'index.mjs')],
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: ['node22'],
  mainFields: ['module', 'main'],
  external: ['@deepseek-ai/dsh-tools'],
  write: false,
  minify: process.env.NODE_ENV === 'production',
  legalComments: 'none',
  banner: {
    js: '/* dsh-finreport host bundle — generated by plugin-src/host/build.mjs; do not edit. */',
  },
});
const bundled = result.outputFiles?.[0]?.text;
if (!bundled) throw new Error('esbuild did not produce a host bundle');

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, bundled, 'utf8');
console.log(`Wrote ${outputPath}`);
