/* dsh-finreport host bundle — generated by plugin-src/host/build.mjs; do not edit. */

// plugin-src/host/index.mjs
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join, resolve } from "node:path";

// plugin-src/host/report.mjs
var UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";
var WEEKDAYS_CN = ["\u5468\u4E00", "\u5468\u4E8C", "\u5468\u4E09", "\u5468\u56DB", "\u5468\u4E94", "\u5468\u516D", "\u5468\u65E5"];
var MARKETS = [
  ["^GSPC", "S&P 500", "us"],
  ["^DJI", "\u9053\u743C\u65AF", "us"],
  ["^IXIC", "\u7EB3\u65AF\u8FBE\u514B", "us"],
  ["^STOXX50E", "Euro Stoxx 50", "eu"],
  ["^GDAXI", "\u5FB7\u56FDDAX", "eu"],
  ["^FCHI", "\u6CD5\u56FDCAC 40", "eu"],
  ["^AEX", "\u8377\u5170AEX", "eu"],
  ["^N225", "\u65E5\u7ECF225", "asia"],
  ["^HSI", "\u6052\u751F\u6307\u6570", "asia"],
  ["000001.SS", "\u4E0A\u8BC1\u6307\u6570", "asia"],
  ["^KS11", "\u97E9\u56FDKOSPI", "asia"],
  ["EURUSD=X", "\u6B27\u5143/\u7F8E\u5143", "fx"],
  ["USDCNY=X", "\u7F8E\u5143/\u4EBA\u6C11\u5E01", "fx"],
  ["GBPUSD=X", "\u82F1\u9551/\u7F8E\u5143", "fx"],
  ["USDJPY=X", "\u7F8E\u5143/\u65E5\u5143", "fx"],
  ["GC=F", "\u9EC4\u91D1 (COMEX)", "comm"],
  ["CL=F", "WTI\u539F\u6CB9", "comm"],
  ["BZ=F", "\u5E03\u4F26\u7279\u539F\u6CB9", "comm"],
  ["BTC-USD", "\u6BD4\u7279\u5E01", "crypto"],
  ["ETH-USD", "\u4EE5\u592A\u574A", "crypto"]
];
var GROUP_ORDER = ["us", "eu", "asia", "fx", "comm", "crypto"];
var GROUP_META = {
  us: ["\u{1F1FA}\u{1F1F8} \u7F8E\u80A1", 2],
  eu: ["\u{1F1EA}\u{1F1FA} \u6B27\u80A1", 2],
  asia: ["\u{1F30F} \u4E9A\u6D32", 2],
  fx: ["\u{1F4B1} \u5916\u6C47", 4],
  comm: ["\u{1F947} \u5927\u5B97\u5546\u54C1", 1],
  crypto: ["\u{1FA99} \u52A0\u5BC6\u8D27\u5E01", 0]
};
var SYMBOL_TZ = {
  "^GSPC": "America/New_York",
  "^DJI": "America/New_York",
  "^IXIC": "America/New_York",
  "^STOXX50E": "Europe/Zurich",
  "^GDAXI": "Europe/Berlin",
  "^FCHI": "Europe/Paris",
  "^AEX": "Europe/Amsterdam",
  "^N225": "Asia/Tokyo",
  "^HSI": "Asia/Hong_Kong",
  "000001.SS": "Asia/Shanghai",
  "^KS11": "Asia/Seoul",
  "EURUSD=X": "Europe/London",
  "USDCNY=X": "Europe/London",
  "GBPUSD=X": "Europe/London",
  "USDJPY=X": "Europe/London",
  "GC=F": "America/New_York",
  "CL=F": "America/New_York",
  "BZ=F": "America/New_York",
  "BTC-USD": "UTC",
  "ETH-USD": "UTC"
};
var NEWS_QUERIES = [
  ["market", 'stock market OR "S&P 500" OR Wall Street OR Nasdaq when:1d', "en-US", "US"],
  ["macro", '("Federal Reserve" OR Fed OR inflation OR "interest rate") when:1d', "en-US", "US"],
  ["europe", "(Europe OR eurozone OR DAX OR CAC OR AEX) markets when:1d", "en-GB", "GB"],
  ["asia", '(China OR Japan OR "Hong Kong" OR "Asia markets") when:1d', "en-US", "US"]
];
var SOURCE_WEIGHTS = {
  Reuters: 10,
  Bloomberg: 10,
  WSJ: 10,
  "Financial Times": 10,
  CNBC: 9,
  MarketWatch: 8,
  "Investing.com": 8,
  AP: 8,
  Fortune: 8,
  "Barron's": 8,
  "The Economist": 8,
  Nikkei: 9,
  "South China Morning Post": 8,
  Caixin: 8,
  "Yahoo Finance": 7,
  "Business Insider": 7,
  BBC: 7,
  "The Guardian": 7,
  Forbes: 7,
  "Bloomberg Quint": 8,
  Benzinga: 7,
  "Seeking Alpha": 6
};
var BAD_WORDS = ["google news", "top stories", "videos", "live updates"];
async function fetchText(url, { timeout = 12e3, retries = 2, signal } = {}) {
  let last;
  for (let i = 0; i < retries; i += 1) {
    try {
      const ctrl = new AbortController();
      const timer = setTimeout(() => ctrl.abort(), timeout);
      const res = await fetch(url, {
        headers: { "User-Agent": UA, Accept: "*/*" },
        signal: signal ?? ctrl.signal
      });
      clearTimeout(timer);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.text();
    } catch (err) {
      last = err;
      await new Promise((r) => setTimeout(r, 1200 * (i + 1)));
    }
  }
  throw last;
}
var fetchJson = async (url, opts) => JSON.parse(await fetchText(url, opts));
function fmtDateTime(ts, tzName) {
  const dt = new Intl.DateTimeFormat("en-CA", {
    timeZone: tzName,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false
  }).format(new Date(ts));
  const [date, time] = dt.split(", ");
  const [y, m, d] = date.trim().split("-");
  return { date: `${y}-${m}-${d}`, time: time.trim(), dateCN: `${Number(m)}/${Number(d)}` };
}
function formatNumber(value, decimals) {
  return decimals <= 0 ? value.toLocaleString("en-US", { maximumFractionDigits: 0 }) : value.toLocaleString("en-US", { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
}
async function yahooQuote(symbol) {
  const url = `https://query2.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?interval=1d&range=5d`;
  try {
    const data = await fetchJson(url);
    const res = data.chart?.result?.[0];
    if (!res) return null;
    const meta = res.meta ?? {};
    const closes = (res.indicators?.quote?.[0]?.close ?? []).filter((c) => c != null);
    const price = meta.regularMarketPrice;
    let prev = meta.previousClose;
    if (prev == null && closes.length >= 2) prev = closes[closes.length - 2];
    if (price == null || prev == null || prev === 0) return null;
    return {
      price: Number(price),
      prev: Number(prev),
      ts: meta.regularMarketTime ? meta.regularMarketTime * 1e3 : Date.now(),
      tz: SYMBOL_TZ[symbol] ?? meta.exchangeTimezoneName ?? "UTC"
    };
  } catch {
    return null;
  }
}
async function coingeckoFallback() {
  try {
    const data = await fetchJson("https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd&include_24hr_change=true", { retries: 1 });
    const out = {};
    for (const [key, label] of [["bitcoin", "BTC-USD"], ["ethereum", "ETH-USD"]]) {
      const price = data[key]?.usd;
      if (price) {
        const chg = data[key]?.usd_24h_change;
        out[label] = { price: Number(price), prev: chg ? price / (1 + chg / 100) : price, ts: Date.now(), tz: "UTC" };
      }
    }
    return out;
  } catch {
    return {};
  }
}
async function buildMarketSection() {
  const quotes = /* @__PURE__ */ new Map();
  for (const [symbol, display, group] of MARKETS) {
    const q = await yahooQuote(symbol);
    if (q) quotes.set(symbol, { display, group, ...q });
    await new Promise((r) => setTimeout(r, 220));
  }
  const cg = await coingeckoFallback();
  for (const [label, q] of Object.entries(cg)) {
    if (!quotes.has(label)) {
      quotes.set(label, {
        display: label === "BTC-USD" ? "\u6BD4\u7279\u5E01" : "\u4EE5\u592A\u574A",
        group: "crypto",
        ...q
      });
    }
  }
  const now = /* @__PURE__ */ new Date();
  const todayBJ = fmtDateTime(now.getTime(), "Asia/Shanghai").date;
  const lines = [];
  for (const group of GROUP_ORDER) {
    const items = [...quotes.entries()].filter(([, v]) => v.group === group);
    if (!items.length) continue;
    const [title, decimals] = GROUP_META[group];
    let label;
    if (group === "us" || group === "eu") label = "\u4E0A\u65E5\u6536\u76D8";
    else if (group === "asia") {
      label = items.every(([, v]) => fmtDateTime(v.ts, SYMBOL_TZ[v.symbol] ?? "UTC").date === todayBJ) ? "\u4ECA\u65E5\u76D8\u4E2D" : "\u6700\u65B0";
    } else label = "\u6700\u65B0";
    lines.push(`
${title} \xB7 ${label}`);
    for (const [symbol, v] of items) {
      const pct = v.prev ? (v.price - v.prev) / v.prev * 100 : 0;
      const arrow = pct >= 0 ? "\u25B2" : "\u25BC";
      let tzLabel, tzForTime;
      if (group === "asia") {
        tzLabel = "\u5317\u4EAC";
        tzForTime = "Asia/Shanghai";
      } else if (group === "us") {
        tzLabel = "\u7F8E\u4E1C";
        tzForTime = "America/New_York";
      } else if (group === "eu") {
        tzLabel = "\u6B27\u6D32";
        tzForTime = SYMBOL_TZ[symbol] ?? "Europe/Berlin";
      } else if (group === "fx") {
        tzLabel = "\u4F26\u6566";
        tzForTime = "Europe/London";
      } else if (group === "comm") {
        tzLabel = "\u7F8E\u4E1C";
        tzForTime = "America/New_York";
      } else {
        tzLabel = "UTC";
        tzForTime = "UTC";
      }
      const qt = fmtDateTime(v.ts, tzForTime);
      lines.push(`\u25B8 ${v.display.padEnd(10)} ${formatNumber(v.price, decimals).padStart(14)}  ${arrow}${Math.abs(pct).toFixed(2)}%  (${tzLabel} ${qt.dateCN} ${qt.time})`);
    }
  }
  return lines.join("\n");
}
function normalizeTitle(title) {
  return title.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff ]/g, "").replace(/\s+/g, " ").trim();
}
function parseRssItems(xml) {
  const items = [];
  const itemRe = /<item>([\s\S]*?)<\/item>/g;
  let m;
  while ((m = itemRe.exec(xml)) !== null) {
    const body = m[1];
    const title = (body.match(/<title>([\s\S]*?)<\/title>/) || [])[1] ?? "";
    const pub = (body.match(/<pubDate>([\s\S]*?)<\/pubDate>/) || [])[1] ?? "";
    const srcMatch = body.match(/<source[^>]*>([\s\S]*?)<\/source>/);
    const src = srcMatch ? srcMatch[1].trim() : "";
    const link = (body.match(/<link>([\s\S]*?)<\/link>/) || [])[1] ?? "";
    const titleText = title.replace(/<!\[CDATA\[|\]\]>/g, "").trim();
    if (!titleText || !pub) continue;
    const ts = Date.parse(pub);
    if (Number.isNaN(ts)) continue;
    if (BAD_WORDS.some((w) => titleText.toLowerCase().includes(w))) continue;
    items.push({ title: titleText, src, link, ts });
  }
  return items;
}
function xmlUnescape(s) {
  return s.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&apos;/g, "'").replace(/&amp;/g, "&");
}
async function fetchNews(limit = 8) {
  const now = Date.now();
  const pool = [];
  for (const [, query, hl, gl] of NEWS_QUERIES) {
    const url = "https://news.google.com/rss/search?" + new URLSearchParams({ q: query, hl, gl, ceid: `${gl}:${hl.slice(-2)}` });
    try {
      const xml = await fetchText(url, { retries: 1 });
      pool.push(...parseRssItems(xml));
    } catch {
    }
  }
  const seen = /* @__PURE__ */ new Map();
  for (const it of pool) {
    const norm = normalizeTitle(xmlUnescape(it.title));
    if (!norm || norm.length < 15) continue;
    const key = norm.slice(0, 60);
    if (!seen.has(key)) seen.set(key, it);
  }
  const ranked = [...seen.values()].map((it) => ({
    ...it,
    score: (SOURCE_WEIGHTS[it.src] ?? 5) - Math.max(0, (now - it.ts) / 36e5) * 1.2
  })).sort((a, b) => b.score - a.score).slice(0, limit);
  const ago = (ts) => {
    const secs = Math.max(0, Math.floor((now - ts) / 1e3));
    if (secs < 3600) return `${Math.max(1, Math.floor(secs / 60))}\u5206\u949F\u524D`;
    if (secs < 86400) return `${Math.floor(secs / 3600)}\u5C0F\u65F6\u524D`;
    return `${Math.floor(secs / 86400)}\u5929\u524D`;
  };
  const lines = [];
  ranked.forEach((it, i) => {
    const title = it.title.length > 110 ? `${it.title.slice(0, 107)}\u2026` : it.title;
    lines.push(`${i + 1}. ${title}`);
    lines.push(`   \xB7 ${it.src || "\u65B0\u95FB"} \xB7 ${ago(it.ts)}`);
  });
  return lines.length ? lines.join("\n") : "\uFF08\u6682\u65E0\u6293\u53D6\u5230\u65B0\u95FB\uFF0C\u8BF7\u7A0D\u540E\u91CD\u8BD5\uFF09";
}
function buildCalendarSection(events, monthlyNote, timeZone) {
  const now = /* @__PURE__ */ new Date();
  const todayStr = fmtDateTime(now.getTime(), timeZone).date;
  const today = /* @__PURE__ */ new Date(`${todayStr}T00:00:00`);
  const upcoming = [];
  for (const ev of events ?? []) {
    const start = /* @__PURE__ */ new Date(`${ev.date}T00:00:00`);
    const end = ev.end ? /* @__PURE__ */ new Date(`${ev.end}T00:00:00`) : start;
    if (start <= today && today <= end) upcoming.push({ off: 0, ev, start });
    else if (today < start && start <= new Date(today.getTime() + 3 * 864e5)) {
      upcoming.push({ off: Math.round((start - today) / 864e5), ev, start });
    }
  }
  upcoming.sort((a, b) => a.off - b.off);
  const lines = [];
  if (!upcoming.length) lines.push("\u4ECA\u65E5\u65E0\u5DF2\u6392\u5B9A\u7684\u592E\u884C\u91CD\u5927\u4E8B\u4EF6");
  const flags = { US: "\u{1F1FA}\u{1F1F8}", EU: "\u{1F1EA}\u{1F1FA}", CN: "\u{1F1E8}\u{1F1F3}", JP: "\u{1F1EF}\u{1F1F5}", GB: "\u{1F1EC}\u{1F1E7}", DE: "\u{1F1E9}\u{1F1EA}", FR: "\u{1F1EB}\u{1F1F7}", NL: "\u{1F1F3}\u{1F1F1}" };
  for (const { off, ev, start } of upcoming) {
    const when = off === 0 ? "\u4ECA\u65E5" : `${off}\u5929\u540E`;
    const d = fmtDateTime(start.getTime(), timeZone);
    const line = `\u25B8 ${when} (${d.dateCN}) ${flags[ev.country] ?? ""} ${ev.name}` + (ev.detail ? `\uFF08${ev.detail}\uFF09` : "");
    lines.push(line);
  }
  if (monthlyNote) lines.push(`
\u{1F4CC} \u6708\u5EA6\u5E38\u89C4\uFF1A${monthlyNote}`);
  return lines.join("\n");
}
async function generateReport({ events, monthlyNote, timeZone = "Europe/Amsterdam", maxNews = 8 } = {}) {
  const now = /* @__PURE__ */ new Date();
  const ams = fmtDateTime(now.getTime(), timeZone);
  const bj = fmtDateTime(now.getTime(), "Asia/Shanghai");
  const dateCN = `${Number(ams.date.slice(5, 7))}\u6708${Number(ams.date.slice(8, 10))}\u65E5 ${WEEKDAYS_CN[now.getDay() === 0 ? 6 : now.getDay() - 1]}`;
  const [market, news, cal] = await Promise.all([
    buildMarketSection(),
    fetchNews(maxNews),
    Promise.resolve(buildCalendarSection(events, monthlyNote, timeZone))
  ]);
  return [
    `\u{1F4CA} *\u8D22\u7ECF\u65E5\u62A5* \xB7 ${dateCN}`,
    `\u{1F557} \u963F\u59C6\u65AF\u7279\u4E39 ${ams.time} \xB7 \u5317\u4EAC\u65F6\u95F4 ${bj.dateCN} ${bj.time}`,
    "",
    "\u2501\u2501\u2501\u2501\u2501 \u{1F310} \u5168\u7403\u5E02\u573A \u2501\u2501\u2501\u2501\u2501",
    market,
    "",
    "\u2501\u2501\u2501\u2501\u2501 \u{1F4F0} \u4ECA\u65E5\u8981\u95FB \u2501\u2501\u2501\u2501\u2501",
    news,
    "",
    "\u2501\u2501\u2501\u2501\u2501 \u{1F4C5} \u5B8F\u89C2\u65E5\u5386 \u2501\u2501\u2501\u2501\u2501",
    cal,
    "",
    "\u2501\u2501\u2501\u2501\u2501",
    "\u6570\u636E\u6E90: Yahoo Finance / CoinGecko / Google News",
    "\u4EC5\u4F5C\u4FE1\u606F\u53C2\u8003\uFF0C\u4E0D\u6784\u6210\u6295\u8D44\u5EFA\u8BAE"
  ].join("\n");
}

// plugin-src/host/delivery.mjs
function envelope(payload, method, channel) {
  return {
    type: "client-request",
    rpcId: `finreport-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    method,
    payload
  };
}
async function sendViaWhatsapp({ baseUrl, botId, jid, text, timeout = 3e4 }) {
  if (!baseUrl || !botId || !jid || !text) {
    throw new Error("whatsapp delivery requires baseUrl/botId/jid/text");
  }
  const url = `${baseUrl.replace(/\/$/, "")}/whatsapp/bot.sendText`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(envelope({ botId, jid, text }, "bot.sendText")),
    signal: AbortSignal.timeout(timeout)
  });
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`whatsapp endpoint HTTP ${res.status}: ${body.slice(0, 300)}`);
  }
  const result = await res.json();
  const inner = result?.result ?? {};
  if (!inner.ok) {
    throw new Error(`whatsapp rpc error ${inner.error?.code ?? "unknown"}: ${inner.error?.message ?? ""}`);
  }
  return { sent: true, jid };
}
function createDeliverer(config) {
  if (typeof config?.deliver === "function") return config.deliver;
  const whatsapp = config?.whatsapp ?? {};
  return (text) => sendViaWhatsapp({
    baseUrl: whatsapp.baseUrl ?? "http://127.0.0.1:3080",
    botId: whatsapp.botId,
    jid: whatsapp.jid,
    text
  });
}

// plugin-src/host/index.mjs
var name = "dsh-finreport-host";
var inject = ["connection", "timer"];
var FINREPORT_RPC_CHANNEL = "/finreport";
var FINREPORT_ENDPOINTS = Object.freeze({
  generate: "report.generate",
  send: "report.send",
  status: "report.status"
});
var DEFAULT_EVENTS = [
  { date: "2026-01-27", end: "2026-01-28", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 1/28 14:00" },
  { date: "2026-02-04", end: "2026-02-05", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", country: "EU", detail: "\u51B3\u8BAE 2/5 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-03-17", end: "2026-03-18", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 3/18 14:00" },
  { date: "2026-03-18", end: "2026-03-19", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", country: "EU", detail: "\u51B3\u8BAE 3/19 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-04-28", end: "2026-04-29", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 4/29 14:00" },
  { date: "2026-04-29", end: "2026-04-30", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", country: "EU", detail: "\u51B3\u8BAE 4/30 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-06-10", end: "2026-06-11", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", country: "EU", detail: "\u51B3\u8BAE 6/11 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-06-16", end: "2026-06-17", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 6/17 14:00" },
  { date: "2026-07-22", end: "2026-07-23", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", country: "EU", detail: "\u51B3\u8BAE 7/23 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-07-28", end: "2026-07-29", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 7/29 14:00" },
  { date: "2026-09-09", end: "2026-09-10", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", country: "EU", detail: "\u51B3\u8BAE 9/10 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-09-15", end: "2026-09-16", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 9/16 14:00" },
  { date: "2026-10-27", end: "2026-10-28", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 10/28 14:00" },
  { date: "2026-10-28", end: "2026-10-29", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", country: "EU", detail: "\u51B3\u8BAE 10/29 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-12-08", end: "2026-12-09", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 12/9 14:00" },
  { date: "2026-12-16", end: "2026-12-17", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", country: "EU", detail: "\u51B3\u8BAE 12/17 \u6CD5\u5170\u514B\u798F 14:15" }
];
var DEFAULT_MONTHLY_NOTE = "\u6BCF\u6708\u5E38\u89C4\u6570\u636E\uFF08\u7EA6\uFF09\uFF1A\u7F8E\u56FD\u975E\u519C\u5C31\u4E1A\u62A5\u544A\uFF08\u9996\u4E2A\u5468\u4E94\uFF09\xB7 \u7F8E\u56FDCPI\uFF08\u6708\u4E2D\uFF0C\u4EE5BLS\u516C\u5E03\u4E3A\u51C6\uFF09\xB7 \u4E2D\u56FDLPR\uFF08\u6BCF\u670820\u65E5\u524D\u540E\uFF09\xB7 OPEC+ \u6708\u5EA6\u4EA7\u91CF\u4F1A\u8BAE";
function zonedParts(ts, tz) {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false
  }).formatToParts(new Date(ts));
  const get = (t) => Number(parts.find((p) => p.type === t).value);
  return { y: get("year"), mo: get("month"), d: get("day"), h: get("hour"), mi: get("minute"), s: get("second") };
}
function tzOffsetMs(ts, tz) {
  const parts = new Intl.DateTimeFormat("en-US", { timeZone: tz, timeZoneName: "longOffset" }).formatToParts(new Date(ts));
  const name2 = (parts.find((p) => p.type === "timeZoneName")?.value ?? "").trim();
  const mm = name2.match(/(\d{1,2})(?::(\d{2}))?/);
  if (!mm) return 0;
  const sign = name2.startsWith("GMT-") ? -1 : 1;
  return sign * ((Number(mm[1]) * 60 + Number(mm[2] ?? 0)) * 6e4);
}
function nextRunMs(now = /* @__PURE__ */ new Date(), hhmm = "08:00", tz = "Europe/Amsterdam") {
  const [h, m] = String(hhmm).split(":").map(Number);
  if (!Number.isInteger(h) || !Number.isInteger(m) || h < 0 || h > 23 || m < 0 || m > 59) {
    throw new Error(`invalid schedule time: ${hhmm}`);
  }
  for (let off = 0; off < 4; off += 1) {
    const day = new Date(now.getTime() + off * 864e5);
    const p = zonedParts(day.getTime(), tz);
    const utcCandidate = Date.UTC(p.y, p.mo - 1, p.d, h, m);
    const instant = utcCandidate - tzOffsetMs(utcCandidate, tz);
    if (instant > now.getTime()) return instant;
  }
  throw new Error("unable to compute next run time");
}
function defaultDataDir(config) {
  return config?.dataDir ?? join(process.env.DSH_HOME ?? join(homedir(), ".dsh"), "integrations", "dsh-finreport");
}
var FinreportStore = class {
  constructor(dir) {
    this.dir = dir;
  }
  statePath() {
    return join(this.dir, "state.json");
  }
  eventsPath() {
    return join(this.dir, "events.json");
  }
  async init({ events, monthlyNote }) {
    await mkdir(this.dir, { recursive: true, mode: 448 });
    try {
      await readFile(this.eventsPath(), "utf8");
    } catch {
      await writeFile(this.eventsPath(), JSON.stringify(
        { events: events ?? DEFAULT_EVENTS, monthlyNote: monthlyNote ?? DEFAULT_MONTHLY_NOTE },
        null,
        2
      ) + "\n", { encoding: "utf8", mode: 384 });
    }
  }
  async loadEvents() {
    try {
      const raw = JSON.parse(await readFile(this.eventsPath(), "utf8"));
      return {
        events: Array.isArray(raw.events) ? raw.events : DEFAULT_EVENTS,
        monthlyNote: typeof raw.monthlyNote === "string" ? raw.monthlyNote : DEFAULT_MONTHLY_NOTE
      };
    } catch {
      return { events: DEFAULT_EVENTS, monthlyNote: DEFAULT_MONTHLY_NOTE };
    }
  }
  async loadState() {
    try {
      return JSON.parse(await readFile(this.statePath(), "utf8")) ?? {};
    } catch {
      return {};
    }
  }
  async saveState(patch) {
    const next = { ...await this.loadState(), ...patch };
    await writeFile(this.statePath(), JSON.stringify(next, null, 2) + "\n", {
      encoding: "utf8",
      mode: 384
    });
    return next;
  }
};
function isRecord(v) {
  return v !== null && typeof v === "object" && !Array.isArray(v);
}
function exactKeys(v, allowed) {
  return isRecord(v) && Object.keys(v).every((k) => allowed.includes(k));
}
function createFinreportRpcHandler(api, { status = () => ({}) } = {}) {
  for (const method of ["generate", "send", "status"]) {
    if (typeof api[method] !== "function") throw new TypeError(`finreport api missing ${method}`);
  }
  return async (endpoint, payload) => {
    if (!Object.values(FINREPORT_ENDPOINTS).includes(endpoint)) {
      return { ok: false, error: { code: "bad-request", message: "Unknown finreport endpoint." } };
    }
    if (!exactKeys(payload, []) && endpoint !== FINREPORT_ENDPOINTS.generate) {
      return { ok: false, error: { code: "bad-request", message: `${endpoint} does not accept fields.` } };
    }
    if (endpoint === FINREPORT_ENDPOINTS.generate && !exactKeys(payload, ["maxNews"])) {
      return { ok: false, error: { code: "bad-request", message: "report.generate accepts only maxNews." } };
    }
    try {
      let value;
      if (endpoint === FINREPORT_ENDPOINTS.generate) value = { text: await api.generate(payload) };
      else if (endpoint === FINREPORT_ENDPOINTS.send) value = await api.send();
      else value = await status();
      return { ok: true, value };
    } catch (error) {
      return {
        ok: false,
        error: { code: error?.code ?? "finreport-operation-failed", message: String(error?.message ?? error) }
      };
    }
  };
}
async function apply(ctx, config = {}) {
  const schedule = config.schedule ?? "08:00";
  const timeZone = config.timezone ?? "Europe/Amsterdam";
  const enabled = config.enabled !== false;
  const maxNews = config.maxNews ?? 8;
  const dir = resolve(defaultDataDir(config));
  const store = new FinreportStore(dir);
  await store.init({ events: config.events, monthlyNote: config.monthlyNote });
  const deliver = createDeliverer(config);
  const log = typeof ctx.logger === "function" ? ctx.logger("dsh-finreport") : console;
  let lastError = null;
  let nextRunAt = null;
  let running = false;
  let scheduleDispose = null;
  const todayInTz = () => {
    const p = zonedParts(Date.now(), timeZone);
    return `${p.y}-${String(p.mo).padStart(2, "0")}-${String(p.d).padStart(2, "0")}`;
  };
  const generate = async (payload = {}) => {
    const cal = await store.loadEvents();
    return generateReport({
      events: cal.events,
      monthlyNote: cal.monthlyNote,
      timeZone,
      maxNews: Number.isInteger(payload?.maxNews) ? payload.maxNews : maxNews
    });
  };
  const run = async ({ record = true } = {}) => {
    if (running) return { skipped: true, reason: "already running" };
    running = true;
    try {
      const text = await generate();
      const state = await store.loadState();
      const today = todayInTz();
      if (record && state.lastSentDate === today) {
        return { skipped: true, reason: `already sent for ${today}` };
      }
      const result = await deliver(text);
      if (record) {
        await store.saveState({ lastSentDate: today, lastSentAt: (/* @__PURE__ */ new Date()).toISOString() });
      }
      lastError = null;
      return { ...result, date: today };
    } catch (error) {
      lastError = String(error?.message ?? error);
      throw error;
    } finally {
      running = false;
    }
  };
  const scheduleNext = () => {
    if (scheduleDispose) {
      scheduleDispose();
      scheduleDispose = null;
    }
    if (!enabled) {
      nextRunAt = null;
      return;
    }
    let ms;
    try {
      ms = nextRunMs(/* @__PURE__ */ new Date(), schedule, timeZone) - Date.now();
    } catch (error) {
      lastError = `schedule: ${error.message}`;
      return;
    }
    nextRunAt = new Date(Date.now() + ms).toISOString();
    scheduleDispose = ctx.timer.timeout(async () => {
      scheduleDispose = null;
      try {
        await run();
      } catch (error) {
        log.warn?.(`scheduled run failed: ${String(error?.message ?? error)}`);
      } finally {
        scheduleNext();
      }
    }, ms);
  };
  const status = async () => {
    const state = await store.loadState();
    return {
      enabled,
      schedule,
      timezone: timeZone,
      maxNews,
      dataDir: dir,
      lastSentDate: state.lastSentDate ?? null,
      lastSentAt: state.lastSentAt ?? null,
      nextRunAt,
      lastError,
      running
    };
  };
  const api = { generate, send: () => run(), status };
  const disposeRpc = ctx.connection.rpc.handle(
    FINREPORT_RPC_CHANNEL,
    createFinreportRpcHandler(api, { status }),
    { authority: config.rpcAuthority ?? "loopback" }
  );
  scheduleNext();
  ctx.effect(() => () => {
    disposeRpc();
    if (scheduleDispose) {
      scheduleDispose();
      scheduleDispose = null;
    }
  }, "dsh-finreport: cleanup");
  return { name, status, generate, run, scheduleNext };
}
var index_default = { name, inject, apply };
export {
  DEFAULT_EVENTS,
  DEFAULT_MONTHLY_NOTE,
  FINREPORT_ENDPOINTS,
  FINREPORT_RPC_CHANNEL,
  FinreportStore,
  apply,
  createFinreportRpcHandler,
  index_default as default,
  inject,
  name,
  nextRunMs
};
