/* dsh-finreport host bundle — generated by plugin-src/host/build.mjs; do not edit. */

// plugin-src/host/index.mjs
import { mkdir, readFile as readFile2, writeFile } from "node:fs/promises";
import { homedir as homedir2 } from "node:os";
import { join as join2, resolve } from "node:path";
import { defineTool } from "@deepseek-ai/dsh-tools";

// plugin-src/host/report.mjs
var UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";
var MARKETS = [
  // [symbol, zh, en, group]
  ["^GSPC", "S&P 500", "S&P 500", "us"],
  ["^DJI", "\u9053\u743C\u65AF", "Dow Jones", "us"],
  ["^IXIC", "\u7EB3\u65AF\u8FBE\u514B", "Nasdaq", "us"],
  ["^STOXX50E", "Euro Stoxx 50", "Euro Stoxx 50", "eu"],
  ["^GDAXI", "\u5FB7\u56FDDAX", "DAX 40", "eu"],
  ["^FCHI", "\u6CD5\u56FDCAC 40", "CAC 40", "eu"],
  ["^AEX", "\u8377\u5170AEX", "AEX (Amsterdam)", "eu"],
  ["^N225", "\u65E5\u7ECF225", "Nikkei 225", "asia"],
  ["^HSI", "\u6052\u751F\u6307\u6570", "Hang Seng", "asia"],
  ["000001.SS", "\u4E0A\u8BC1\u6307\u6570", "Shanghai Composite", "asia"],
  ["^KS11", "\u97E9\u56FDKOSPI", "KOSPI", "asia"],
  ["EURUSD=X", "\u6B27\u5143/\u7F8E\u5143", "EUR/USD", "fx"],
  ["USDCNY=X", "\u7F8E\u5143/\u4EBA\u6C11\u5E01", "USD/CNY", "fx"],
  ["GBPUSD=X", "\u82F1\u9551/\u7F8E\u5143", "GBP/USD", "fx"],
  ["USDJPY=X", "\u7F8E\u5143/\u65E5\u5143", "USD/JPY", "fx"],
  ["GC=F", "\u9EC4\u91D1 (COMEX)", "Gold (COMEX)", "comm"],
  ["CL=F", "WTI\u539F\u6CB9", "WTI Crude", "comm"],
  ["BZ=F", "\u5E03\u4F26\u7279\u539F\u6CB9", "Brent Crude", "comm"],
  ["BTC-USD", "\u6BD4\u7279\u5E01", "Bitcoin", "crypto"],
  ["ETH-USD", "\u4EE5\u592A\u574A", "Ethereum", "crypto"]
];
var GROUP_ORDER = ["us", "eu", "asia", "fx", "comm", "crypto"];
var GROUP_TITLES = {
  us: ["\u{1F1FA}\u{1F1F8} \u7F8E\u80A1", "\u{1F1FA}\u{1F1F8} US Stocks"],
  eu: ["\u{1F1EA}\u{1F1FA} \u6B27\u80A1", "\u{1F1EA}\u{1F1FA} Europe"],
  asia: ["\u{1F30F} \u4E9A\u6D32", "\u{1F30F} Asia"],
  fx: ["\u{1F4B1} \u5916\u6C47", "\u{1F4B1} FX"],
  comm: ["\u{1F947} \u5927\u5B97\u5546\u54C1", "\u{1F947} Commodities"],
  crypto: ["\u{1FA99} \u52A0\u5BC6\u8D27\u5E01", "\u{1FA99} Crypto"]
};
var GROUP_DECIMALS = { us: 2, eu: 2, asia: 2, fx: 4, comm: 1, crypto: 0 };
var I18N = {
  zh: {
    title: "\u{1F4CA} *\u8D22\u7ECF\u65E5\u62A5* \xB7 {date}",
    timeLine: "\u{1F557} \u963F\u59C6\u65AF\u7279\u4E39 {ams} \xB7 \u5317\u4EAC\u65F6\u95F4 {bj}",
    markets: "\u2501\u2501\u2501\u2501\u2501 \u{1F310} \u5168\u7403\u5E02\u573A \u2501\u2501\u2501\u2501\u2501",
    news: "\u2501\u2501\u2501\u2501\u2501 \u{1F4F0} \u4ECA\u65E5\u8981\u95FB \u2501\u2501\u2501\u2501\u2501",
    calendar: "\u2501\u2501\u2501\u2501\u2501 \u{1F4C5} \u5B8F\u89C2\u65E5\u5386 \u2501\u2501\u2501\u2501\u2501",
    usLabel: "\u4E0A\u65E5\u6536\u76D8",
    euLabel: "\u4E0A\u65E5\u6536\u76D8",
    asiaToday: "\u4ECA\u65E5\u76D8\u4E2D",
    latest: "\u6700\u65B0",
    noCalendarEvents: "\u4ECA\u65E5\u65E0\u5DF2\u6392\u5B9A\u7684\u592E\u884C\u91CD\u5927\u4E8B\u4EF6",
    monthlyPrefix: "\u{1F4CC} \u6708\u5EA6\u5E38\u89C4\uFF1A",
    weekdays: ["\u5468\u4E00", "\u5468\u4E8C", "\u5468\u4E09", "\u5468\u56DB", "\u5468\u4E94", "\u5468\u516D", "\u5468\u65E5"],
    tz: { asia: "\u5317\u4EAC", us: "\u7F8E\u4E1C", eu: "\u6B27\u6D32", fx: "\u4F26\u6566", comm: "\u7F8E\u4E1C", crypto: "UTC" },
    ago: (min, hr, day) => min != null ? `${min}\u5206\u949F\u524D` : hr != null ? `${hr}\u5C0F\u65F6\u524D` : `${day}\u5929\u524D`,
    footer: ["\u6570\u636E\u6E90: Yahoo Finance / CoinGecko / Google News", "\u4EC5\u4F5C\u4FE1\u606F\u53C2\u8003\uFF0C\u4E0D\u6784\u6210\u6295\u8D44\u5EFA\u8BAE"]
  },
  en: {
    title: "\u{1F4CA} *Daily Financial Report* \xB7 {date}",
    timeLine: "\u{1F557} Amsterdam {ams} \xB7 Beijing {bj}",
    markets: "\u2501\u2501\u2501\u2501\u2501 \u{1F310} Global Markets \u2501\u2501\u2501\u2501\u2501",
    news: "\u2501\u2501\u2501\u2501\u2501 \u{1F4F0} Top News \u2501\u2501\u2501\u2501\u2501",
    calendar: "\u2501\u2501\u2501\u2501\u2501 \u{1F4C5} Macro Calendar \u2501\u2501\u2501\u2501\u2501",
    usLabel: "Last Close",
    euLabel: "Last Close",
    asiaToday: "Today",
    latest: "Latest",
    noCalendarEvents: "No major central-bank events scheduled today",
    monthlyPrefix: "\u{1F4CC} Monthly recurring: ",
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    tz: { asia: "BJ", us: "ET", eu: "EU", fx: "LON", comm: "ET", crypto: "UTC" },
    ago: (min, hr, day) => min != null ? `${min}min ago` : hr != null ? `${hr}h ago` : `${day}d ago`,
    footer: ["Sources: Yahoo Finance / CoinGecko / Google News", "For information only, not investment advice"]
  }
};
var SYMBOL_TZ = {
  "^GSPC": "America/New_York",
  "^DJI": "America/New_York",
  "^IXIC": "America/New_York",
  "^STOXX50E": "Europe/Zurich",
  "^GDAXI": "Europe/Berlin",
  "^FCHI": "Europe/Paris",
  "^AEX": "Europe/Amsterdam",
  "^N225": "Asia/Tokyo",
  "^HSI": "Asia/Hong_Kong",
  "000001.SS": "Asia/Shanghai",
  "^KS11": "Asia/Seoul",
  "EURUSD=X": "Europe/London",
  "USDCNY=X": "Europe/London",
  "GBPUSD=X": "Europe/London",
  "USDJPY=X": "Europe/London",
  "GC=F": "America/New_York",
  "CL=F": "America/New_York",
  "BZ=F": "America/New_York",
  "BTC-USD": "UTC",
  "ETH-USD": "UTC"
};
var NEWS_QUERIES = [
  ["market", 'stock market OR "S&P 500" OR Wall Street OR Nasdaq when:1d', "en-US", "US"],
  ["macro", '("Federal Reserve" OR Fed OR inflation OR "interest rate") when:1d', "en-US", "US"],
  ["europe", "(Europe OR eurozone OR DAX OR CAC OR AEX) markets when:1d", "en-GB", "GB"],
  ["asia", '(China OR Japan OR "Hong Kong" OR "Asia markets") when:1d', "en-US", "US"]
];
var SOURCE_WEIGHTS = {
  Reuters: 10,
  Bloomberg: 10,
  WSJ: 10,
  "Financial Times": 10,
  CNBC: 9,
  MarketWatch: 8,
  "Investing.com": 8,
  AP: 8,
  Fortune: 8,
  "Barron's": 8,
  "The Economist": 8,
  Nikkei: 9,
  "South China Morning Post": 8,
  Caixin: 8,
  "Yahoo Finance": 7,
  "Business Insider": 7,
  BBC: 7,
  "The Guardian": 7,
  Forbes: 7,
  "Bloomberg Quint": 8,
  Benzinga: 7,
  "Seeking Alpha": 6
};
var BAD_WORDS = ["google news", "top stories", "videos", "live updates"];
function normalizeLang(language) {
  const lang = String(language ?? "zh").toLowerCase();
  return lang === "en" || lang === "english" ? "en" : "zh";
}
async function fetchText(url, { timeout = 12e3, retries = 2, signal } = {}) {
  let last;
  for (let i = 0; i < retries; i += 1) {
    try {
      const ctrl = new AbortController();
      const timer = setTimeout(() => ctrl.abort(), timeout);
      const res = await fetch(url, {
        headers: { "User-Agent": UA, Accept: "*/*" },
        signal: signal ?? ctrl.signal
      });
      clearTimeout(timer);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.text();
    } catch (err) {
      last = err;
      await new Promise((r) => setTimeout(r, 1200 * (i + 1)));
    }
  }
  throw last;
}
var fetchJson = async (url, opts) => JSON.parse(await fetchText(url, opts));
function fmtDateTime(ts, tzName) {
  const dt = new Intl.DateTimeFormat("en-CA", {
    timeZone: tzName,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false
  }).format(new Date(ts));
  const [date, time] = dt.split(", ");
  const [y, m, d] = date.trim().split("-");
  return { date: `${y}-${m}-${d}`, time: time.trim(), dateCN: `${Number(m)}/${Number(d)}` };
}
function formatNumber(value, decimals) {
  return decimals <= 0 ? value.toLocaleString("en-US", { maximumFractionDigits: 0 }) : value.toLocaleString("en-US", { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
}
async function yahooQuote(symbol) {
  const url = `https://query2.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?interval=1d&range=5d`;
  try {
    const data = await fetchJson(url);
    const res = data.chart?.result?.[0];
    if (!res) return null;
    const meta = res.meta ?? {};
    const closes = (res.indicators?.quote?.[0]?.close ?? []).filter((c) => c != null);
    const price = meta.regularMarketPrice;
    let prev = meta.previousClose;
    if (prev == null && closes.length >= 2) prev = closes[closes.length - 2];
    if (price == null || prev == null || prev === 0) return null;
    return {
      price: Number(price),
      prev: Number(prev),
      ts: meta.regularMarketTime ? meta.regularMarketTime * 1e3 : Date.now(),
      tz: SYMBOL_TZ[symbol] ?? meta.exchangeTimezoneName ?? "UTC"
    };
  } catch {
    return null;
  }
}
async function coingeckoFallback() {
  try {
    const data = await fetchJson("https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd&include_24hr_change=true", { retries: 1 });
    const out = {};
    for (const [key, label] of [["bitcoin", "BTC-USD"], ["ethereum", "ETH-USD"]]) {
      const price = data[key]?.usd;
      if (price) {
        const chg = data[key]?.usd_24h_change;
        out[label] = { price: Number(price), prev: chg ? price / (1 + chg / 100) : price, ts: Date.now(), tz: "UTC" };
      }
    }
    return out;
  } catch {
    return {};
  }
}
async function buildMarketSection(language) {
  const i18n = I18N[language];
  const quotes = /* @__PURE__ */ new Map();
  for (const [symbol, zh, en, group] of MARKETS) {
    const q = await yahooQuote(symbol);
    if (q) quotes.set(symbol, { display: language === "en" ? en : zh, group, ...q });
    await new Promise((r) => setTimeout(r, 220));
  }
  const cg = await coingeckoFallback();
  for (const [label, q] of Object.entries(cg)) {
    if (!quotes.has(label)) {
      quotes.set(label, {
        display: language === "en" ? label === "BTC-USD" ? "Bitcoin" : "Ethereum" : label === "BTC-USD" ? "\u6BD4\u7279\u5E01" : "\u4EE5\u592A\u574A",
        group: "crypto",
        ...q
      });
    }
  }
  const now = /* @__PURE__ */ new Date();
  const todayBJ = fmtDateTime(now.getTime(), "Asia/Shanghai").date;
  const lines = [];
  for (const group of GROUP_ORDER) {
    const items = [...quotes.entries()].filter(([, v]) => v.group === group);
    if (!items.length) continue;
    const [title] = GROUP_TITLES[group];
    const titleText = language === "en" ? GROUP_TITLES[group][1] : title;
    let label;
    if (group === "us" || group === "eu") label = i18n.usLabel;
    else if (group === "asia") {
      label = items.every(([, v]) => fmtDateTime(v.ts, SYMBOL_TZ[v.symbol] ?? "UTC").date === todayBJ) ? i18n.asiaToday : i18n.latest;
    } else label = i18n.latest;
    lines.push(`
${titleText} \xB7 ${label}`);
    const decimals = GROUP_DECIMALS[group];
    for (const [symbol, v] of items) {
      const pct = v.prev ? (v.price - v.prev) / v.prev * 100 : 0;
      const arrow = pct >= 0 ? "\u25B2" : "\u25BC";
      let tzLabel, tzForTime;
      if (group === "asia") {
        tzLabel = i18n.tz.asia;
        tzForTime = "Asia/Shanghai";
      } else if (group === "us") {
        tzLabel = i18n.tz.us;
        tzForTime = "America/New_York";
      } else if (group === "eu") {
        tzLabel = i18n.tz.eu;
        tzForTime = SYMBOL_TZ[symbol] ?? "Europe/Berlin";
      } else if (group === "fx") {
        tzLabel = i18n.tz.fx;
        tzForTime = "Europe/London";
      } else if (group === "comm") {
        tzLabel = i18n.tz.comm;
        tzForTime = "America/New_York";
      } else {
        tzLabel = i18n.tz.crypto;
        tzForTime = "UTC";
      }
      const qt = fmtDateTime(v.ts, tzForTime);
      lines.push(`\u25B8 ${v.display.padEnd(12)} ${formatNumber(v.price, decimals).padStart(14)}  ${arrow}${Math.abs(pct).toFixed(2)}%  (${tzLabel} ${qt.dateCN} ${qt.time})`);
    }
  }
  return lines.join("\n");
}
function normalizeTitle(title) {
  return title.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff ]/g, "").replace(/\s+/g, " ").trim();
}
function parseRssItems(xml) {
  const items = [];
  const itemRe = /<item>([\s\S]*?)<\/item>/g;
  let m;
  while ((m = itemRe.exec(xml)) !== null) {
    const body = m[1];
    const title = (body.match(/<title>([\s\S]*?)<\/title>/) || [])[1] ?? "";
    const pub = (body.match(/<pubDate>([\s\S]*?)<\/pubDate>/) || [])[1] ?? "";
    const srcMatch = body.match(/<source[^>]*>([\s\S]*?)<\/source>/);
    const src = srcMatch ? srcMatch[1].trim() : "";
    const link = (body.match(/<link>([\s\S]*?)<\/link>/) || [])[1] ?? "";
    const titleText = title.replace(/<!\[CDATA\[|\]\]>/g, "").trim();
    if (!titleText || !pub) continue;
    const ts = Date.parse(pub);
    if (Number.isNaN(ts)) continue;
    if (BAD_WORDS.some((w) => titleText.toLowerCase().includes(w))) continue;
    items.push({ title: titleText, src, link, ts });
  }
  return items;
}
function xmlUnescape(s) {
  return s.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&apos;/g, "'").replace(/&amp;/g, "&");
}
async function fetchNews(language, limit = 8) {
  const i18n = I18N[language];
  const now = Date.now();
  const pool = [];
  for (const [, query, hl, gl] of NEWS_QUERIES) {
    const url = "https://news.google.com/rss/search?" + new URLSearchParams({ q: query, hl, gl, ceid: `${gl}:${hl.slice(-2)}` });
    try {
      const xml = await fetchText(url, { retries: 1 });
      pool.push(...parseRssItems(xml));
    } catch {
    }
  }
  const seen = /* @__PURE__ */ new Map();
  for (const it of pool) {
    const norm = normalizeTitle(xmlUnescape(it.title));
    if (!norm || norm.length < 15) continue;
    const key = norm.slice(0, 60);
    if (!seen.has(key)) seen.set(key, it);
  }
  const ranked = [...seen.values()].map((it) => ({
    ...it,
    score: (SOURCE_WEIGHTS[it.src] ?? 5) - Math.max(0, (now - it.ts) / 36e5) * 1.2
  })).sort((a, b) => b.score - a.score).slice(0, limit);
  const ago = (ts) => {
    const secs = Math.max(0, Math.floor((now - ts) / 1e3));
    if (secs < 3600) return i18n.ago(Math.max(1, Math.floor(secs / 60)), null, null);
    if (secs < 86400) return i18n.ago(null, Math.floor(secs / 3600), null);
    return i18n.ago(null, null, Math.floor(secs / 86400));
  };
  const lines = [];
  ranked.forEach((it, i) => {
    const title = it.title.length > 110 ? `${it.title.slice(0, 107)}\u2026` : it.title;
    lines.push(`${i + 1}. ${title}`);
    lines.push(`   \xB7 ${it.src || "news"} \xB7 ${ago(it.ts)}`);
  });
  return lines.length ? lines.join("\n") : language === "en" ? "(No news fetched, please retry later)" : "\uFF08\u6682\u65E0\u6293\u53D6\u5230\u65B0\u95FB\uFF0C\u8BF7\u7A0D\u540E\u91CD\u8BD5\uFF09";
}
function buildCalendarSection({ events, monthlyNote, monthlyNoteEn, timeZone, language = "zh" }) {
  const i18n = I18N[language];
  const now = /* @__PURE__ */ new Date();
  const todayStr = fmtDateTime(now.getTime(), timeZone).date;
  const today = /* @__PURE__ */ new Date(`${todayStr}T00:00:00`);
  const upcoming = [];
  for (const ev of events ?? []) {
    const start = /* @__PURE__ */ new Date(`${ev.date}T00:00:00`);
    const end = ev.end ? /* @__PURE__ */ new Date(`${ev.end}T00:00:00`) : start;
    if (start <= today && today <= end) upcoming.push({ off: 0, ev, start });
    else if (today < start && start <= new Date(today.getTime() + 3 * 864e5)) {
      upcoming.push({ off: Math.round((start - today) / 864e5), ev, start });
    }
  }
  upcoming.sort((a, b) => a.off - b.off);
  const lines = [];
  if (!upcoming.length) lines.push(i18n.noCalendarEvents);
  const flags = { US: "\u{1F1FA}\u{1F1F8}", EU: "\u{1F1EA}\u{1F1FA}", CN: "\u{1F1E8}\u{1F1F3}", JP: "\u{1F1EF}\u{1F1F5}", GB: "\u{1F1EC}\u{1F1E7}", DE: "\u{1F1E9}\u{1F1EA}", FR: "\u{1F1EB}\u{1F1F7}", NL: "\u{1F1F3}\u{1F1F1}" };
  for (const { off, ev, start } of upcoming) {
    const when = off === 0 ? language === "en" ? "Today" : "\u4ECA\u65E5" : language === "en" ? `in ${off} day${off > 1 ? "s" : ""}` : `${off}\u5929\u540E`;
    const d = fmtDateTime(start.getTime(), timeZone);
    const name2 = language === "en" ? ev.nameEn ?? ev.name : ev.name;
    const line = `\u25B8 ${when} (${d.dateCN}) ${flags[ev.country] ?? ""} ${name2}` + (ev.detail ? `\uFF08${ev.detail}\uFF09` : "");
    lines.push(line);
  }
  const note = language === "en" ? monthlyNoteEn ?? monthlyNote : monthlyNote;
  if (note) lines.push(`
${i18n.monthlyPrefix}${note}`);
  return lines.join("\n");
}
async function generateReport({
  events,
  monthlyNote,
  monthlyNoteEn,
  timeZone = "Europe/Amsterdam",
  maxNews = 8,
  language = "zh"
} = {}) {
  const lang = normalizeLang(language);
  const i18n = I18N[lang];
  const now = /* @__PURE__ */ new Date();
  const ams = fmtDateTime(now.getTime(), timeZone);
  const bj = fmtDateTime(now.getTime(), "Asia/Shanghai");
  const weekday = lang === "en" ? i18n.weekdays[now.getDay() === 0 ? 6 : now.getDay() - 1] : i18n.weekdays[now.getDay() === 0 ? 6 : now.getDay() - 1];
  const date = lang === "en" ? `${weekday}, ${new Intl.DateTimeFormat("en-US", { month: "short" }).format(now)} ${now.getDate()}` : `${now.getMonth() + 1}\u6708${now.getDate()}\u65E5 ${weekday}`;
  const [market, news, cal] = await Promise.all([
    buildMarketSection(lang),
    fetchNews(lang, maxNews),
    Promise.resolve(buildCalendarSection({ events, monthlyNote, monthlyNoteEn, timeZone, language: lang }))
  ]);
  return [
    i18n.title.replace("{date}", date),
    i18n.timeLine.replace("{ams}", `${Number(ams.date.slice(5, 7))}/${Number(ams.date.slice(8, 10))} ${ams.time}`).replace("{bj}", `${bj.dateCN} ${bj.time}`),
    "",
    i18n.markets,
    market,
    "",
    i18n.news,
    news,
    "",
    i18n.calendar,
    cal,
    "",
    "\u2501\u2501\u2501\u2501\u2501",
    ...i18n.footer
  ].join("\n");
}

// plugin-src/host/delivery.mjs
function rpcEnvelope(method, payload) {
  return {
    type: "client-request",
    rpcId: `finreport-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    method,
    payload
  };
}
function targetPayload(channel, target) {
  if (channel === "whatsapp") {
    return { botId: target.botId, jid: target.jid, text: target.text };
  }
  const t = {};
  if (channel === "telegram") t.chatId = target.chatId;
  else if (channel === "discord") t.channelId = target.channelId;
  else if (channel === "feishu") {
    t.receiveId = target.receiveId;
    if (target.receiveIdType) t.receiveIdType = target.receiveIdType;
  } else if (channel === "dingtalk") t.sessionWebhook = target.sessionWebhook;
  else if (channel === "wecom") t.chatId = target.chatId;
  else if (channel === "qq") {
    if (target.openid) t.openid = target.openid;
    if (target.group_openid) t.group_openid = target.group_openid;
  } else if (channel === "weixin") t.toUserId = target.toUserId;
  else throw new Error(`unsupported delivery channel: ${channel}`);
  return { botId: target.botId, target: t, text: target.text };
}
async function sendToTarget({ baseUrl, channel, target, text, timeout = 3e4 }) {
  const payload = targetPayload(channel, { ...target, text });
  const url = `${baseUrl.replace(/\/$/, "")}/${channel}/bot.sendText`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(rpcEnvelope("bot.sendText", payload)),
    signal: AbortSignal.timeout(timeout)
  });
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`${channel} endpoint HTTP ${res.status}: ${body.slice(0, 300)}`);
  }
  const result = await res.json();
  const inner = result?.result ?? {};
  if (!inner.ok) {
    throw new Error(`${channel} rpc error ${inner.error?.code ?? "unknown"}: ${inner.error?.message ?? ""}`);
  }
  return { sent: true, channel, botId: target.botId };
}
function normalizeTargets(config) {
  if (Array.isArray(config?.delivery)) return config.delivery.filter((d) => d && d.channel);
  if (config?.whatsapp?.botId && config?.whatsapp?.jid) {
    return [{
      channel: "whatsapp",
      botId: config.whatsapp.botId,
      jid: config.whatsapp.jid,
      baseUrl: config.whatsapp.baseUrl
    }];
  }
  return [];
}
function describeTargets(config) {
  return normalizeTargets(config).map((t) => {
    const id = t.jid ?? t.chatId ?? t.channelId ?? t.receiveId ?? t.toUserId ?? t.openid ?? t.group_openid ?? t.sessionWebhook ?? "?";
    const masked = String(id).length > 10 ? `${String(id).slice(0, 6)}\u2026${String(id).slice(-4)}` : String(id);
    return { channel: t.channel, botId: t.botId, target: masked };
  });
}
function conversationTarget(channel, conversationId, kind) {
  switch (channel) {
    case "whatsapp":
      return { jid: conversationId };
    case "telegram":
      return { chatId: /^\d+$/.test(conversationId) ? Number(conversationId) : conversationId };
    case "discord":
      return { channelId: conversationId };
    case "feishu":
      return { receiveId: conversationId };
    case "wecom":
      return { chatId: conversationId };
    case "qq":
      return kind === "group" ? { group_openid: conversationId } : { openid: conversationId };
    case "weixin":
      return { toUserId: conversationId };
    case "dingtalk":
      return { sessionWebhook: conversationId };
    default:
      return null;
  }
}

// plugin-src/host/session-map.mjs
import { readdir, readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
var CHANNEL_PREFIX = "dsh-";
function defaultDshHome() {
  return process.env.DSH_HOME ?? join(homedir(), ".dsh");
}
async function findConversationBySession(sessionId, { dshHome } = {}) {
  if (!sessionId) return null;
  const integrations = join(dshHome ?? defaultDshHome(), "integrations");
  let channels;
  try {
    channels = await readdir(integrations, { withFileTypes: true });
  } catch {
    return null;
  }
  for (const entry of channels) {
    if (!entry.isDirectory() || !entry.name.startsWith(CHANNEL_PREFIX)) continue;
    const channel = entry.name.slice(CHANNEL_PREFIX.length);
    const botsRoot = join(integrations, entry.name, "bots");
    let bots;
    try {
      bots = await readdir(botsRoot, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const bot of bots) {
      if (!bot.isDirectory()) continue;
      const statePath = join(botsRoot, bot.name, "state.json");
      try {
        const raw = JSON.parse(await readFile(statePath, "utf8"));
        const sessions = raw?.sessions ?? {};
        for (const [key, sid] of Object.entries(sessions)) {
          if (sid !== sessionId) continue;
          const sep = key.indexOf(":");
          return {
            channel,
            botId: bot.name,
            kind: sep > 0 ? key.slice(0, sep) : "direct",
            conversationId: sep > 0 ? key.slice(sep + 1) : key
          };
        }
      } catch {
      }
    }
  }
  return null;
}

// plugin-src/host/index.mjs
var name = "dsh-finreport-host";
var inject = ["connection", "timer", "tools"];
var FINREPORT_RPC_CHANNEL = "/finreport";
var FINREPORT_ENDPOINTS = Object.freeze({
  generate: "report.generate",
  send: "report.send",
  status: "report.status"
});
var DEFAULT_EVENTS = [
  { date: "2026-01-27", end: "2026-01-28", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", nameEn: "US FOMC Meeting", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 1/28 14:00" },
  { date: "2026-02-04", end: "2026-02-05", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", nameEn: "ECB Rate Decision", country: "EU", detail: "\u51B3\u8BAE 2/5 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-03-17", end: "2026-03-18", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", nameEn: "US FOMC Meeting", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 3/18 14:00" },
  { date: "2026-03-18", end: "2026-03-19", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", nameEn: "ECB Rate Decision", country: "EU", detail: "\u51B3\u8BAE 3/19 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-04-28", end: "2026-04-29", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", nameEn: "US FOMC Meeting", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 4/29 14:00" },
  { date: "2026-04-29", end: "2026-04-30", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", nameEn: "ECB Rate Decision", country: "EU", detail: "\u51B3\u8BAE 4/30 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-06-10", end: "2026-06-11", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", nameEn: "ECB Rate Decision", country: "EU", detail: "\u51B3\u8BAE 6/11 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-06-16", end: "2026-06-17", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", nameEn: "US FOMC Meeting", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 6/17 14:00" },
  { date: "2026-07-22", end: "2026-07-23", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", nameEn: "ECB Rate Decision", country: "EU", detail: "\u51B3\u8BAE 7/23 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-07-28", end: "2026-07-29", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", nameEn: "US FOMC Meeting", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 7/29 14:00" },
  { date: "2026-09-09", end: "2026-09-10", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", nameEn: "ECB Rate Decision", country: "EU", detail: "\u51B3\u8BAE 9/10 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-09-15", end: "2026-09-16", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", nameEn: "US FOMC Meeting", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 9/16 14:00" },
  { date: "2026-10-27", end: "2026-10-28", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", nameEn: "US FOMC Meeting", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 10/28 14:00" },
  { date: "2026-10-28", end: "2026-10-29", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", nameEn: "ECB Rate Decision", country: "EU", detail: "\u51B3\u8BAE 10/29 \u6CD5\u5170\u514B\u798F 14:15" },
  { date: "2026-12-08", end: "2026-12-09", name: "\u7F8E\u8054\u50A8FOMC\u8BAE\u606F\u4F1A\u8BAE", nameEn: "US FOMC Meeting", country: "US", detail: "\u5229\u7387\u51B3\u8BAE\u7F8E\u4E1C 12/9 14:00" },
  { date: "2026-12-16", end: "2026-12-17", name: "\u6B27\u6D32\u592E\u884C(ECB)\u5229\u7387\u51B3\u8BAE", nameEn: "ECB Rate Decision", country: "EU", detail: "\u51B3\u8BAE 12/17 \u6CD5\u5170\u514B\u798F 14:15" }
];
var DEFAULT_MONTHLY_NOTE = "\u6BCF\u6708\u5E38\u89C4\u6570\u636E\uFF08\u7EA6\uFF09\uFF1A\u7F8E\u56FD\u975E\u519C\u5C31\u4E1A\u62A5\u544A\uFF08\u9996\u4E2A\u5468\u4E94\uFF09\xB7 \u7F8E\u56FDCPI\uFF08\u6708\u4E2D\uFF0C\u4EE5BLS\u516C\u5E03\u4E3A\u51C6\uFF09\xB7 \u4E2D\u56FDLPR\uFF08\u6BCF\u670820\u65E5\u524D\u540E\uFF09\xB7 OPEC+ \u6708\u5EA6\u4EA7\u91CF\u4F1A\u8BAE";
var DEFAULT_MONTHLY_NOTE_EN = "Monthly recurring (approx.): US Nonfarm Payrolls (first Friday) \xB7 US CPI (mid-month, per BLS) \xB7 China LPR (around the 20th) \xB7 OPEC+ monthly output meeting";
function zonedParts(ts, tz) {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false
  }).formatToParts(new Date(ts));
  const get = (t) => Number(parts.find((p) => p.type === t).value);
  return { y: get("year"), mo: get("month"), d: get("day"), h: get("hour"), mi: get("minute"), s: get("second") };
}
function tzOffsetMs(ts, tz) {
  const parts = new Intl.DateTimeFormat("en-US", { timeZone: tz, timeZoneName: "longOffset" }).formatToParts(new Date(ts));
  const name2 = (parts.find((p) => p.type === "timeZoneName")?.value ?? "").trim();
  const mm = name2.match(/(\d{1,2})(?::(\d{2}))?/);
  if (!mm) return 0;
  const sign = name2.startsWith("GMT-") ? -1 : 1;
  return sign * ((Number(mm[1]) * 60 + Number(mm[2] ?? 0)) * 6e4);
}
function nextRunMs(now = /* @__PURE__ */ new Date(), hhmm = "08:00", tz = "Europe/Amsterdam") {
  const [h, m] = String(hhmm).split(":").map(Number);
  if (!Number.isInteger(h) || !Number.isInteger(m) || h < 0 || h > 23 || m < 0 || m > 59) {
    throw new Error(`invalid schedule time: ${hhmm}`);
  }
  for (let off = 0; off < 4; off += 1) {
    const day = new Date(now.getTime() + off * 864e5);
    const p = zonedParts(day.getTime(), tz);
    const utcCandidate = Date.UTC(p.y, p.mo - 1, p.d, h, m);
    const instant = utcCandidate - tzOffsetMs(utcCandidate, tz);
    if (instant > now.getTime()) return instant;
  }
  throw new Error("unable to compute next run time");
}
function defaultDataDir(config) {
  return config?.dataDir ?? join2(process.env.DSH_HOME ?? join2(homedir2(), ".dsh"), "integrations", "dsh-finreport");
}
var FinreportStore = class {
  constructor(dir) {
    this.dir = dir;
  }
  statePath() {
    return join2(this.dir, "state.json");
  }
  eventsPath() {
    return join2(this.dir, "events.json");
  }
  async init({ events, monthlyNote, monthlyNoteEn }) {
    await mkdir(this.dir, { recursive: true, mode: 448 });
    try {
      await readFile2(this.eventsPath(), "utf8");
    } catch {
      await writeFile(this.eventsPath(), JSON.stringify({
        events: events ?? DEFAULT_EVENTS,
        monthlyNote: monthlyNote ?? DEFAULT_MONTHLY_NOTE,
        monthlyNoteEn: monthlyNoteEn ?? DEFAULT_MONTHLY_NOTE_EN
      }, null, 2) + "\n", { encoding: "utf8", mode: 384 });
    }
  }
  async loadEvents() {
    try {
      const raw = JSON.parse(await readFile2(this.eventsPath(), "utf8"));
      return {
        events: Array.isArray(raw.events) ? raw.events : DEFAULT_EVENTS,
        monthlyNote: typeof raw.monthlyNote === "string" ? raw.monthlyNote : DEFAULT_MONTHLY_NOTE,
        monthlyNoteEn: typeof raw.monthlyNoteEn === "string" ? raw.monthlyNoteEn : DEFAULT_MONTHLY_NOTE_EN
      };
    } catch {
      return { events: DEFAULT_EVENTS, monthlyNote: DEFAULT_MONTHLY_NOTE, monthlyNoteEn: DEFAULT_MONTHLY_NOTE_EN };
    }
  }
  async loadState() {
    try {
      return JSON.parse(await readFile2(this.statePath(), "utf8")) ?? {};
    } catch {
      return {};
    }
  }
  async saveState(patch) {
    const next = { ...await this.loadState(), ...patch };
    await writeFile(this.statePath(), JSON.stringify(next, null, 2) + "\n", {
      encoding: "utf8",
      mode: 384
    });
    return next;
  }
};
function isRecord(v) {
  return v !== null && typeof v === "object" && !Array.isArray(v);
}
function exactKeys(v, allowed) {
  return isRecord(v) && Object.keys(v).every((k) => allowed.includes(k));
}
function validLanguage(v) {
  return v === void 0 || v === "zh" || v === "en";
}
function validTarget(v) {
  return v === void 0 || v === "all" || typeof v === "number" && Number.isInteger(v) && v >= 0;
}
function createFinreportRpcHandler(api, { status = () => ({}) } = {}) {
  for (const method of ["generate", "send", "status"]) {
    if (typeof api[method] !== "function") throw new TypeError(`finreport api missing ${method}`);
  }
  const bad = (message) => ({ ok: false, error: { code: "bad-request", message } });
  return async (endpoint, payload) => {
    if (!Object.values(FINREPORT_ENDPOINTS).includes(endpoint)) {
      return bad("Unknown finreport endpoint.");
    }
    if (!isRecord(payload)) return bad("Payload must be an object.");
    if (endpoint === FINREPORT_ENDPOINTS.generate) {
      if (!exactKeys(payload, ["language", "maxNews"]) || !validLanguage(payload.language)) {
        return bad('report.generate accepts only { language?: "zh"|"en", maxNews?: number }.');
      }
    } else if (endpoint === FINREPORT_ENDPOINTS.send) {
      if (!exactKeys(payload, ["language", "target"]) || !validLanguage(payload.language) || !validTarget(payload.target)) {
        return bad('report.send accepts only { language?: "zh"|"en", target?: number|"all" }.');
      }
    } else if (!exactKeys(payload, [])) {
      return bad("report.status does not accept fields.");
    }
    try {
      let value;
      if (endpoint === FINREPORT_ENDPOINTS.generate) value = { text: await api.generate(payload) };
      else if (endpoint === FINREPORT_ENDPOINTS.send) value = await api.send(payload);
      else value = await status();
      return { ok: true, value };
    } catch (error) {
      return {
        ok: false,
        error: { code: error?.code ?? "finreport-operation-failed", message: String(error?.message ?? error) }
      };
    }
  };
}
async function apply(ctx, config = {}) {
  const globalSchedule = config.schedule ?? "08:00";
  const globalTimeZone = config.timezone ?? "Europe/Amsterdam";
  const enabled = config.enabled !== false;
  const maxNews = config.maxNews ?? 8;
  const baseUrl = (config?.baseUrl ?? config?.whatsapp?.baseUrl ?? "http://127.0.0.1:3080").replace(/\/$/, "");
  const dir = resolve(defaultDataDir(config));
  const store = new FinreportStore(dir);
  await store.init({ events: config.events, monthlyNote: config.monthlyNote, monthlyNoteEn: config.monthlyNoteEn });
  const log = typeof ctx.logger === "function" ? ctx.logger("dsh-finreport") : console;
  const targets = normalizeTargets(config);
  if (!targets.length) {
    log.warn?.("no delivery targets configured (set config.delivery or config.whatsapp)");
  }
  let lastError = null;
  let running = false;
  const timers = /* @__PURE__ */ new Map();
  let toolDispose = null;
  const todayInTz = (tz) => {
    const p = zonedParts(Date.now(), tz);
    return `${p.y}-${String(p.mo).padStart(2, "0")}-${String(p.d).padStart(2, "0")}`;
  };
  const targetLanguage = (t, override) => {
    const lang = String(override ?? t.language ?? "zh").toLowerCase();
    return lang === "en" || lang === "english" ? "en" : "zh";
  };
  const generate = async (payload = {}) => {
    const cal = await store.loadEvents();
    return generateReport({
      events: cal.events,
      monthlyNote: cal.monthlyNote,
      monthlyNoteEn: cal.monthlyNoteEn,
      timeZone: globalTimeZone,
      maxNews: Number.isInteger(payload?.maxNews) ? payload.maxNews : maxNews,
      language: payload?.language ?? "zh"
    });
  };
  const sendOne = async (idx, { language } = {}) => {
    const t = targets[idx];
    if (!t) {
      const err = new Error(`delivery target ${idx} not found`);
      err.code = "bad-target";
      throw err;
    }
    const lang = targetLanguage(t, language);
    const text = await generate({ language: lang, maxNews });
    const result = await sendToTarget({
      baseUrl: t.baseUrl ?? baseUrl,
      channel: t.channel,
      target: t,
      text
    });
    return { ...result, language: lang, date: todayInTz(t.timezone ?? globalTimeZone) };
  };
  const run = async (payload = {}) => {
    if (running) return { skipped: true, reason: "already running" };
    running = true;
    try {
      if (typeof config.deliver === "function") {
        const language2 = payload?.language;
        const today = todayInTz(globalTimeZone);
        const state = await store.loadState();
        if (state.lastSentDate === today) {
          return { targets: [{ skipped: true, reason: `already sent for ${today}` }] };
        }
        const text = await generate({ language: language2 });
        await config.deliver(text);
        await store.saveState({ lastSentDate: today, lastSentAt: (/* @__PURE__ */ new Date()).toISOString() });
        lastError = null;
        return { targets: [{ sent: true, language: targetLanguage({}, language2), custom: true }] };
      }
      const language = payload?.language;
      const pick = payload?.target;
      const idxs = pick === void 0 || pick === "all" ? targets.map((_, i) => i) : [Number(pick)];
      const results = [];
      for (const idx of idxs) {
        const t = targets[idx];
        if (!t) {
          results.push({ target: idx, error: "target not found" });
          continue;
        }
        const today = todayInTz(t.timezone ?? globalTimeZone);
        const state = await store.loadState();
        const key = `${t.channel}:${t.botId}`;
        const sentToday = state.sentByTarget?.[key] === today;
        if (sentToday) {
          results.push({ target: idx, channel: t.channel, botId: t.botId, skipped: true, reason: `already sent for ${today}` });
          continue;
        }
        try {
          const res = await sendOne(idx, { language });
          await store.saveState({
            sentByTarget: { ...state.sentByTarget ?? {}, [key]: today },
            lastSentDate: today,
            lastSentAt: (/* @__PURE__ */ new Date()).toISOString()
          });
          results.push({ target: idx, channel: res.channel, botId: res.botId, sent: true, language: res.language });
        } catch (error) {
          results.push({ target: idx, channel: t.channel, botId: t.botId, sent: false, error: String(error?.message ?? error) });
        }
      }
      lastError = null;
      return { targets: results };
    } catch (error) {
      lastError = String(error?.message ?? error);
      throw error;
    } finally {
      running = false;
    }
  };
  const clearTimers = () => {
    for (const dispose of timers.values()) dispose();
    timers.clear();
  };
  const scheduleTarget = (idx) => {
    const t = targets[idx];
    if (!t || !enabled) return null;
    const tz = t.timezone ?? globalTimeZone;
    const sched = t.schedule ?? globalSchedule;
    let ms;
    try {
      ms = nextRunMs(/* @__PURE__ */ new Date(), sched, tz) - Date.now();
    } catch (error) {
      lastError = `schedule[${idx}]: ${error.message}`;
      return null;
    }
    const prev = timers.get(idx);
    if (prev) prev();
    const nextAt = new Date(Date.now() + ms).toISOString();
    const dispose = ctx.timer.timeout(async () => {
      timers.delete(idx);
      try {
        await run({ target: idx });
      } catch (error) {
        log.warn?.(`target ${idx} scheduled run failed: ${String(error?.message ?? error)}`);
      } finally {
        scheduleTarget(idx);
      }
    }, ms);
    timers.set(idx, dispose);
    return nextAt;
  };
  const scheduleAll = () => {
    clearTimers();
    if (!enabled) return;
    targets.forEach((_, i) => scheduleTarget(i));
  };
  const status = async () => {
    const state = await store.loadState();
    const now = Date.now();
    const perTarget = targets.map((t, i) => {
      const tz = t.timezone ?? globalTimeZone;
      const sched = t.schedule ?? globalSchedule;
      let next = null;
      try {
        next = new Date(nextRunMs(/* @__PURE__ */ new Date(), sched, tz)).toISOString();
      } catch {
      }
      return {
        index: i,
        channel: t.channel,
        botId: t.botId,
        language: targetLanguage(t),
        schedule: sched,
        timezone: tz,
        nextRunAt: next,
        lastSentDate: state.sentByTarget?.[`${t.channel}:${t.botId}`] ?? null
      };
    });
    return {
      enabled,
      schedule: globalSchedule,
      timezone: globalTimeZone,
      maxNews,
      dataDir: dir,
      baseUrl,
      targets: perTarget,
      deliveryTargets: describeTargets(config),
      lastSentDate: state.lastSentDate ?? null,
      lastSentAt: state.lastSentAt ?? null,
      lastError,
      running,
      toolRegistered: toolDispose !== null,
      now
    };
  };
  const api = { generate, send: (p = {}) => run(p), status };
  const disposeRpc = ctx.connection.rpc.handle(
    FINREPORT_RPC_CHANNEL,
    createFinreportRpcHandler(api, { status }),
    { authority: config.rpcAuthority ?? "loopback" }
  );
  if (ctx.tools?.register) {
    const render = (_args, value) => [{ type: "text", text: JSON.stringify(value, null, 2) }];
    toolDispose = ctx.tools.register(defineTool({
      name: "finreport_send",
      description: "Generate and send the daily financial report (\u4E2D\u82F1\u6587\u53EF\u9009). When invoked from an IM chat, it sends the report back to that conversation; otherwise it sends to all configured delivery targets. Use language 'zh' for Chinese or 'en' for English.",
      parameters: {
        language: {
          type: "string",
          description: "Report language: 'zh' (\u4E2D\u6587) or 'en' (English). Defaults to the target's configured language."
        },
        target: {
          type: "string",
          description: 'Optional delivery target index (see /finreport report.status) or "all". Defaults to the current conversation.'
        }
      },
      output: {
        schema: {
          type: "object",
          additionalProperties: false,
          properties: {
            sent: { type: "boolean", required: true },
            targets: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: false,
                properties: {
                  channel: { type: "string" },
                  botId: { type: "string" },
                  sent: { type: "boolean" },
                  skipped: { type: "boolean" },
                  language: { type: "string" },
                  error: { type: "string" }
                }
              }
            },
            note: { type: "string" }
          }
        },
        render
      },
      timeoutMs: 12e4,
      isConcurrencySafe: () => true,
      execute: async (args, exec) => {
        const language = typeof args?.language === "string" ? args.language : void 0;
        const target = typeof args?.target === "string" ? args.target : void 0;
        const sessionId = exec?.agent?.id ? String(exec.agent.id) : null;
        if (sessionId && (target === void 0 || target === "")) {
          const conv = await findConversationBySession(sessionId).catch(() => null);
          if (conv) {
            const tFields = conversationTarget(conv.channel, conv.conversationId, conv.kind);
            if (tFields) {
              const matched = targets.find((t) => t.channel === conv.channel && t.botId === conv.botId);
              const lang = targetLanguage(matched ?? { language: void 0 }, language);
              const text = await generate({ language: lang, maxNews });
              await sendToTarget({
                baseUrl,
                channel: conv.channel,
                target: { botId: conv.botId, ...tFields },
                text
              });
              return {
                sent: true,
                targets: [{ channel: conv.channel, botId: conv.botId, sent: true, language: lang }],
                note: `sent to ${conv.channel} conversation`
              };
            }
          }
        }
        const res = await run({ language, target });
        return {
          sent: true,
          targets: res.targets,
          note: "sent to configured delivery targets"
        };
      }
    }));
  } else {
    log.warn?.('tools service unavailable \u2014 in-chat "finreport_send" tool not registered');
  }
  scheduleAll();
  ctx.effect(() => () => {
    disposeRpc();
    clearTimers();
    if (toolDispose) {
      toolDispose();
      toolDispose = null;
    }
  }, "dsh-finreport: cleanup");
}
var index_default = { name, inject, apply };
export {
  DEFAULT_EVENTS,
  DEFAULT_MONTHLY_NOTE,
  DEFAULT_MONTHLY_NOTE_EN,
  FINREPORT_ENDPOINTS,
  FINREPORT_RPC_CHANNEL,
  FinreportStore,
  apply,
  createFinreportRpcHandler,
  index_default as default,
  inject,
  name,
  nextRunMs
};
